# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "https://niccgag.github.io"

[_.globalMeta]
title = "Nicolas Gagnepain"
description = "Software developer in New Zealand"
longDescription = "Zaggonaut is a retro-inspired theme for Astro, built using TypeScript, TailwindCSS, and Astro."
cardImage = "/images/profile.webp"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "Zaggonaut Projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "/images/profile.webp"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "Zaggonaut 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "/images/profile.webp"

[_.hero]
title = "Nicolas Gagnepain"
subtitle = "Software developer in New Zealand"
image = "/images/profile.webp"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Nicolas Gagnepain"
githubProfile = "https://github.com/niccgag"

[_.texts]
projectsName = "Projects"
viewAll = "View All"
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
